// <auto-generated />
using System;
using Ecologica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecologica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514205442_PopularTrilhaNovamente")]
    partial class PopularTrilhaNovamente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ecologica.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_atividade");

                    b.Property<double>("FatorEmissao")
                        .HasColumnType("REAL")
                        .HasColumnName("fator_emissao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("UnidadeMedida")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("atividades");
                });

            modelBuilder.Entity("Ecologica.Models.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("Ecologica.Models.RegistroCarbonoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_registro");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_registro");

                    b.Property<double>("EmissaoTotal")
                        .HasColumnType("REAL")
                        .HasColumnName("emissao_total");

                    b.Property<int>("IdAtividade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_atividade");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<double>("Quantidade")
                        .HasColumnType("REAL")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("IdAtividade");

                    b.HasIndex("IdUsuario");

                    b.ToTable("registros_carbono");
                });

            modelBuilder.Entity("Ecologica.Models.TrilhaConhecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaBloqueado")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Progresso")
                        .HasColumnType("REAL");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("trilha_progresso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstaBloqueado = false,
                            Progresso = 1.0,
                            Titulo = "Introdução ao CO2"
                        },
                        new
                        {
                            Id = 2,
                            EstaBloqueado = false,
                            Progresso = 0.40000000000000002,
                            Titulo = "Cálculo de Emissões"
                        },
                        new
                        {
                            Id = 3,
                            EstaBloqueado = true,
                            Progresso = 0.0,
                            Titulo = "Desafio Final"
                        });
                });

            modelBuilder.Entity("Ecologica.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pontos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Ecologica.Models.RegistroCarbonoModel", b =>
                {
                    b.HasOne("Ecologica.Models.Atividade", "AtividadeRelacionada")
                        .WithMany()
                        .HasForeignKey("IdAtividade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecologica.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtividadeRelacionada");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
