// <auto-generated />
using System;
using Ecologica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecologica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ecologica.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_atividade");

                    b.Property<double?>("FatorEmissao")
                        .HasColumnType("REAL")
                        .HasColumnName("fator_emissao");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("UnidadeMedida")
                        .HasColumnType("TEXT")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id");

                    b.ToTable("atividades");
                });

            modelBuilder.Entity("Ecologica.Models.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAquisicao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_aquisicao");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("conquistas");
                });

            modelBuilder.Entity("Ecologica.Models.RegistroCarbonoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_registro");

                    b.Property<DateTime?>("DataRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_registro");

                    b.Property<double?>("EmissaoTotal")
                        .HasColumnType("REAL")
                        .HasColumnName("emissao_total");

                    b.Property<int?>("IdAtividade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_atividade");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<double?>("Quantidade")
                        .HasColumnType("REAL")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("IdAtividade");

                    b.HasIndex("IdUsuario");

                    b.ToTable("registros_carbono");
                });

            modelBuilder.Entity("Ecologica.Models.TrilhaConhecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EstaBloqueado")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Progresso")
                        .HasColumnType("REAL");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("trilha_progresso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Aprenda o básico",
                            EstaBloqueado = false,
                            Progresso = 0.0,
                            Titulo = "Introdução ao CO2"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Hora de praticar",
                            EstaBloqueado = true,
                            Progresso = 0.0,
                            Titulo = "Cálculo de Emissões"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Mestre da Ecologia",
                            EstaBloqueado = true,
                            Progresso = 0.0,
                            Titulo = "Desafio Final"
                        });
                });

            modelBuilder.Entity("Ecologica.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Pontos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PosicaoNoMapa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeArvores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Ecologica.Models.Conquista", b =>
                {
                    b.HasOne("Ecologica.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ecologica.Models.RegistroCarbonoModel", b =>
                {
                    b.HasOne("Ecologica.Models.Atividade", "AtividadeRelacionada")
                        .WithMany()
                        .HasForeignKey("IdAtividade");

                    b.HasOne("Ecologica.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("AtividadeRelacionada");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
